initialise_constants;

tr_1 = Transistor(0.5, ...    % V_ds
                0.0, ...    % V_g
                3,   ...    % d_ch
                1,   ...    % d_ox
                0.5, ...    % a
                'm',         0.02*m_e,      ...
                'E_f',       0.1,         ... % eV
                'l_ch',      13,           ...
                'dE',        5e-4,         ... % alternatively: n_energy_steps
                'T',         300,          ...
                'eps_ch',    eps_si,       ...
                'eps_ox',    eps_sio2,     ...
                'l_ds',      '12 lambda',   ...
                'E_g',       1,            ... % eV
                'lambda_ds', 1,   ... % multiple of lambda_ch
                'geometry',  'nano-wire',  ...
                'newton_step_size', 0.3,   ...   
                'self_consistency_limit', 1e-3, ... % eV
                'dopant_type', 'n', ...
                ... %'E_min', 1, ...    % leave out for automatic, adaptive energy
                ... %'E_max', -0.5, ... % depending on E_f, V_ds, and phi
                'coupling_left', 1, ...
                'coupling_right', 1, ...
                'eta', 1e-8 ...
                );

tr_2 = Transistor(0.5, ...    % V_ds
                0.0, ...    % V_g
                3,   ...    % d_ch
                30,   ...    % d_ox
                0.5, ...    % a
                'm',         0.02*m_e,      ...
                'E_f',       0.1,         ... % eV
                'l_ch',      13,           ...
                'dE',        5e-4,         ... % alternatively: n_energy_steps
                'T',         300,          ...
                'eps_ch',    eps_si,       ...
                'eps_ox',    eps_sio2,     ...
                'l_ds',      '12 lambda',   ...
                'E_g',       1,            ... % eV
                'lambda_ds', 1,   ... % multiple of lambda_ch
                'geometry',  'nano-wire',  ...
                'newton_step_size', 0.3,   ...   
                'self_consistency_limit', 1e-3, ... % eV
                'dopant_type', 'n', ...
                ... %'E_min', 1, ...    % leave out for automatic, adaptive energy
                ... %'E_max', -0.5, ... % depending on E_f, V_ds, and phi
                'coupling_left', 1, ...
                'coupling_right', 1, ...
                'eta', 1e-8 ...
                );
%%

V_g_range = 0.0 : 0.05 : 0.5;
n_elem = (0.4 - 0.0)/0.05 + 1;
%V_g_range(n_elem)

[fig_1, current_1, subthr_slope_1, iterations_1] = tr_1.plot_transfer_characteristic(V_g_range);
[fig_2, current_2, subthr_slope_2, iterations_2] = tr_2.plot_transfer_characteristic(V_g_range);
% override subthreshold slope
subthr_slope_1 = helper.subthreshold_slope(V_g_range, current_1, n_elem )
subthr_slope_2 = helper.subthreshold_slope(V_g_range, current_2, n_elem)